<a href="https://colab.research.google.com/github/shilpavv/datascince/blob/master/co1basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3])
print("array type",type(arr))
print("list",arr)
a=np.array([1])
print("1-D",a)
a.ndim
a1=np.array(("apple", "banana", "cherry"))
print("tuple",a1)
a2=np.array([[1,2,3],[4,5,6]])
print("2-D",a2)
print("shape",a2.shape)
a2.shape=3,2
print(a2)

array type <class 'numpy.ndarray'>
list [1 2 3]
1-D [1]
tuple ['apple' 'banana' 'cherry']
2-D [[1 2 3]
 [4 5 6]]
shape (2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a2=np.array([1,2,3,4,5,6])
a2.resize(3,4)
print(a2)


[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [ ]:
from numpy import random

x = random.randint(100)

print(x)

40


In [ ]:
a2=np.array([1,2,3,4,5,6,7,8])
print(a2.reshape(2,4))


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a = np.zeros(3,dtype = int)
print("Matrix a", a)

Matrix a [0 0 0]


In [ ]:
a = np.ones(3,dtype = int)
print("Matrix a", a)

Matrix a [1 1 1]


In [ ]:
a = np.eye(3,dtype = int)
print("Matrix a", a)

Matrix a [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
a = np.arange(0,11)
print("range",a)


range [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.array([2,3])
b=np.array([4,5])
print("add",np.add(a,b))
print("subtract",np.subtract(a,b))
print("subtract",np.subtract(b,a))
print("square",np.power(a,2))

add [6 8]
subtract [-2 -2]
subtract [2 2]
square [4 9]
