<a href="https://colab.research.google.com/github/shilpavv/datascince/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
a=[2,4,6,8,10,12,14,16,18,20]
var=pd.Series(a)
print(var)
b=[3,6,9,12,15,18,21,24,27,30]
vari=pd.Series(b)
print(vari)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
9    20
dtype: int64
0     3
1     6
2     9
3    12
4    15
5    18
6    21
7    24
8    27
9    30
dtype: int64


In [ ]:
import pandas as pd
a= pd.Series([2, 4, 6, 8, 10])
b= pd.Series([1, 3, 5, 7, 9])
c=a+b
print(c)

0     3
1     7
2    11
3    15
4    19
dtype: int64


In [ ]:
a=pd.Series([10,2,4])
print(a)
print(a.loc[2])

0    10
1     2
2     4
dtype: int64
4


In [ ]:
import pandas as pd
var = pd.Series([15,20,30],index=[0,1,2])
print(var)

0    15
1    20
2    30
dtype: int64


In [ ]:
import pandas as pd
var = pd.Series([15,20,30],index=["MCA", "MBA","MTECH"])
print(var)
print("max value:",var.max())
print("min value:",var.min())

MCA      15
MBA      20
MTECH    30
dtype: int64
max value: 30
min value: 15


In [ ]:
#csv files upload and print
import pandas as pd
x=pd.read_csv('/content/data.csv')
print(x.to_string())

In [ ]:
#datagram
import pandas as pd
data = {"percentage":[90,80,70,60],"grade": ["A","B","C","D"]}
x= pd.DataFrame(data,index=["anju","arya","suray","vidya"])
print(x)


       percentage grade
anju           90     A
arya           80     B
suray          70     C
vidya          60     D


In [ ]:
#head function
import pandas as pd
p=pd.read_csv('/content/data.csv')
print(p.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [ ]:
#tail function
import pandas as pd
p=pd.read_csv('/content/data.csv')
print(p.tail())

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


In [ ]:
import pandas as pd
x=pd.read_csv('/content/STUDENT - Sheet1.csv')
print(x.to_string())

     name  class  total mark
0  Abhiha  MTECH         700
1    Sree  BTECH         800
2  shilpa    MCA         700
3   vidya    NaN         900


In [ ]:
import pandas as pd
x=pd.read_csv('/content/STUDENT - Sheet1.csv')
print(x.to_string())
print("head of the file")
print(x.head(2))

     name  class  total mark
0  Abhiha  MTECH         700
1    Sree  BTECH         800
2  shilpa    MCA         700
3   vidya    NaN         900
head of the file
     name  class  total mark
0  Abhiha  MTECH         700
1    Sree  BTECH         800


In [ ]:
import pandas as pd
x=pd.read_csv('/content/STUDENT - Sheet1.csv')
print(x.to_string())
x.drop_duplicates("total mark")
x.dropna()

     name  class  total mark
0  Abhiha  MTECH         700
1    Sree  BTECH         800
2  shilpa    MCA         700
3   vidya    NaN         900


name  class  total mark
0  Abhiha  MTECH         700
1    Sree  BTECH         800
2  shilpa    MCA         700

In [ ]:
import pandas as pd
x=pd.read_csv('/content/STUDENT - Sheet1.csv')
print(x.to_string())
x.corr()

     name  class  total mark
0  Abhiha  MTECH         700
1    Sree  BTECH         800
2  shilpa    MCA         700
3   vidya    NaN         900


total mark
total mark         1.0

In [ ]:
#SVD
import numpy as np
A=np.array([[1,2,3],[4,6,8],[3,6,5]])
print("A:",A)
U,S,V=np.linalg.svd(A)
print("U:",U)
print("S:",S)
print("V:",V)
A_remake=(U @ np.diag(S) @ V)
print(A_remake)

A: [[1 2 3]
 [4 6 8]
 [3 6 5]]
U: [[-0.26277779 -0.32413598 -0.90878144]
 [-0.76423861 -0.50502463  0.40111029]
 [-0.58897129  0.79992874 -0.11500798]]
S: [14.05603597  1.51200527  0.37642098]
V: [[-0.3618834  -0.6150251  -0.70056015]
 [ 0.03674043  0.74150053 -0.6699456 ]
 [ 0.93149908 -0.26818107 -0.24574045]]
[[1. 2. 3.]
 [4. 6. 8.]
 [3. 6. 5.]]


In [ ]:
#transpose of maatrix
import numpy as np
m=np.matrix('[1,4,6;2,4,1;4,8,8;5,3,0]')
print(m)
print("transpose of matrix")
print(m.transpose())

[[1 4 6]
 [2 4 1]
 [4 8 8]
 [5 3 0]]
transpose of matrix
[[1 2 4 5]
 [4 4 8 3]
 [6 1 8 0]]
