<a href="https://colab.research.google.com/github/shilpavv/datascince/blob/master/python_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy
arr=numpy.array([1,2,3,4])
print(arr)

import numpy
arr=numpy.array((1,2,3,4))
print(arr)



[1 2 3 4]
[1 2 3 4]


In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [9]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:

import numpy as np
arr=p.array(42)
print(arr)

42
