<a href="https://colab.research.google.com/github/shilpavv/datascince/blob/master/svd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as p
#create a matrix A
A=p.array([[3,4,5],[1,2,3],[4,2,1]])
#performing svd
U,D,VT=p.linalg.svd(A)
#CHECKING IF WE CAN REMAKE THE ORIGINAL MATRIX USING U,D,VT
Aremake=(U@p.diag(D)@VT)
print(U)
print(D)
print(VT)
print(Aremake)

[[-0.80102553 -0.28301186 -0.52750582]
 [-0.40767885 -0.38736309  0.82689044]
 [-0.43835608  0.87741332  0.19490977]]
[8.770045   2.84251196 0.08022798]
[[-0.52042832 -0.55828357 -0.64612215]
 [ 0.7997344  -0.05345517 -0.59796942]
 [ 0.29929793 -0.82792633  0.47429816]]
[[3. 4. 5.]
 [1. 2. 3.]
 [4. 2. 1.]]
